# mkdocs.yml
site_name: Александра Парамонова · P3122
site_description: Портфолио лабораторных работ
site_author: Александра Парамонова
site_url: https://alexandraparamonova9.github.io

repo_name: alexandraparamonova9.github.io
repo_url: https://github.com/alexandraparamonova9/alexandraparamonova9.github.io

theme:
  name: material
  language: ru
  icon:
    logo: material/code-brackets
    repo: fontawesome/brands/github
  palette:
    # Только светлая тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
  font:
    text: Inter
    code: DM Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.tabs.link

extra_css:
  - custom.css
  - https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap
  - https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&display=swap

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Главная: index.md
  - Обо мне: about.md
  - Лабораторные работы:
      - Лабораторная работа №1: labs/lab1.md
      - Лабораторная работа №2: labs/lab2.md
      - Лабораторная работа №3: labs/lab3.md
      - Лабораторная работа №4: labs/lab4.md
      - Лабораторная работа №5: labs/lab5.md
      - Лабораторная работа №6: labs/lab6.md
      - Лабораторная работа №7: labs/lab7.md
      - Лабораторная работа №8: labs/lab8.md

plugins:
  - search:
      lang: ru
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alexandraparamonova9
    - icon: fontawesome/brands/telegram
      link: https://t.me/aleqxji
    - icon: fontawesome/solid/envelope
      link: mailto:mailParamonova@yandex.ru
  generator: false

copyright: Copyright &copy; 2026 Александра Парамонова